import re

with open("frontend/src/App.jsx", "r") as f:
    c = f.read()

reps = {
    "Unable to Confidently Identify This Medicine": "{t.unable_to_identify}",
    "The image resolution or clarity is too low, or the prescription is too faint to be parsed safely. For your clinical safety, please upload a clearer photo.": "{t.unable_to_identify_desc}",
    "Accessibility Complexity Score": "{t.accessibility_complexity_score}",
    "Difficulty<": "{t.difficulty}<",
    "Jargon Density:": "{t.jargon_density}:",
    "Readability Level:": "{t.readability_level}:",
    "AI Hallucination Safeguard<": "{t.ai_hallucination_safeguard}<",
    "This report was generated by an AI vision model. AI outputs may contain inaccuracies. All medication details <strong>MUST</strong> be verified by a licensed pharmacist or physician before use.": "{t.ai_hallucination_desc}",
    "Polypharmacy Review (Provider Notes)": "{t.polypharmacy_review_provider}",
    "Green Pharmacy Impact": "{t.green_pharmacy_impact}",
    "AI Confidence Score": "{t.ai_confidence_score}",
    "AI Observation": "{t.ai_observation}",
    "Structured Medication Table": "{t.structured_medication_table}",
    "Meds Found": "{t.meds_found}",
    "Medication Name": "{t.medication_name}",
    "Confidence<": "{t.confidence}<",
    "Verify": "{t.verify}",
    "Please verify this reading with a pharmacist.": "{t.please_verify}",
    "Patient Notes:": "{t.patient_notes}:",
    "Clinical Terms Simplified": "{t.clinical_terms_simplified}",
    "means <strong>": "{t.means} <strong>",
    "Advice Explainability Panel": "{t.advice_explainability_panel}",
    "Pharmacist Consultation Recommended": "{t.pharmacist_consultation}",
    "Please consult a licensed pharmacist to verify drug interactions, correct dosages for your age/weight, and any contraindications with your existing conditions or allergies.": "{t.pharmacist_desc}",
    "PDF Report": "{t.pdf_report}",
    "Share on WhatsApp": "{t.share_whatsapp}",
    "Print Instructions": "{t.print_instructions}",
    "Print Report": "{t.print_report}"
}

for k, v in reps.items():
    if k == "This report was generated by an AI vision model. AI outputs may contain inaccuracies. All medication details <strong>MUST</strong> be verified by a licensed pharmacist or physician before use.":
        # we need to be careful with strong tags if the translation doesn't include it.
        # Actually our translation is just a flat string, so we can just replace the whole JSX block content:
        c = c.replace(
            "This report was generated by an AI vision model. AI outputs may contain inaccuracies. All medication details <strong>MUST</strong> be verified by a licensed pharmacist or physician before use.",
            "{t.ai_hallucination_desc}"
        )
    elif k in ["Difficulty<", "AI Hallucination Safeguard<", "Confidence<"]:
        c = c.replace(k, v)
    else:
        # only replace literal matches
        c = c.replace(k, v)

with open("frontend/src/App.jsx", "w") as f:
    f.write(c)

print("Replaced strings.")
