const fs = require('fs');
let app = fs.readFileSync('frontend/src/App.jsx', 'utf8');

const generateHTMLStart = app.indexOf('const generatePDFHTML');
const generateHTMLEnd = app.indexOf('const downloadPDF =') - 1;

if (generateHTMLStart === -1 || generateHTMLEnd === -1) {
  console.log('Error finding function bounds');
  process.exit(1);
}

const newFunction = `const generatePDFHTML = (data) => {
    if (!data) return '';
    const safeArray = (arr) => Array.isArray(arr) ? arr : [];
    
    // Parse individual drugs
    const drugs = safeArray(data.drugs_list);
    let drugRows = '';
    
    if (drugs.length > 0) {
      drugs.forEach((d, idx) => {
        const dosage = (data.drugs_dosage && data.drugs_dosage[d]) || data.dosage || 'N/A';
        const freq = data.frequency || 'N/A';
        const duration = data.duration || 'N/A';
        
        drugRows += \`
          <tr>
            <td style="padding: 16px; border: 1px solid #c7d2fe; text-align: center; color: #334155;">\${idx + 1}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${d}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${dosage}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${freq}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${duration}</td>
          </tr>
        \`;
      });
    } else {
        drugRows = \`
          <tr>
            <td style="padding: 16px; border: 1px solid #c7d2fe; text-align: center; color: #334155;">1</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${data.drug || 'Unknown'}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${data.dosage || 'N/A'}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${data.frequency || 'N/A'}</td>
            <td style="padding: 16px; border: 1px solid #c7d2fe; color: #334155;">\${data.duration || 'N/A'}</td>
          </tr>
        \`;
    }

    const clinicalSummary = \`This prescription contains \${data.drug || 'the listed medications'}. \${data.instructions || ''} \${data.notes || ''}\`;

    let html = \`
    <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; background: #ffffff; padding: 40px; max-width: 900px; margin: 0 auto;">
      <!-- Header -->
      <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px;">
        <div>
          <h1 style="color: #6366f1; margin: 0; font-size: 36px; font-weight: 800; letter-spacing: -0.5px;">RxLens</h1>
          <p style="color: #64748b; margin: 4px 0 0 0; font-size: 16px;">AI-Powered Clinical Prescription Report</p>
        </div>
        <div style="text-align: right; color: #64748b; font-size: 14px; padding-top: 10px;">
          \${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}, \${new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
        </div>
      </div>
      <div style="height: 3px; background-color: #6366f1; margin-bottom: 24px; width: 100%;"></div>

      <!-- AI Hallucination Safeguard -->
      <div style="border: 2px solid #ef4444; background-color: #fef2f2; padding: 16px; margin-bottom: 30px;">
        <p style="color: #dc2626; margin: 0; font-size: 14px; font-style: italic; font-weight: 600; line-height: 1.5;">
          AI HALLUCINATION SAFEGUARD: This report was generated by an AI vision model. AI outputs may contain inaccuracies. All medication details MUST be verified by a licensed pharmacist or physician before use. Do not self-medicate based on this report alone.
        </p>
      </div>

      <!-- Meta Info Table -->
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 40px;">
        <tbody>
          <tr>
            <td style="padding: 12px 0; font-weight: 700; color: #334155; width: 25%; border-bottom: 1px solid #f1f5f9;">AI Engine:</td>
            <td style="padding: 12px 0; color: #334155; border-bottom: 1px solid #f1f5f9;">Google Gemini Flash (Vision Language Model)</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; font-weight: 700; color: #334155; border-bottom: 1px solid #f1f5f9;">Report Type:</td>
            <td style="padding: 12px 0; color: #334155; border-bottom: 1px solid #f1f5f9;">Prescription Digitization & Clinical Safety</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; font-weight: 700; color: #334155; border-bottom: 1px solid #f1f5f9;">Confidence:</td>
            <td style="padding: 12px 0; color: #334155; border-bottom: 1px solid #f1f5f9;">Source grounding via multi-step pharmacist AI prompt</td>
          </tr>
        </tbody>
      </table>

      <!-- Prescribed Medication Regimen -->
      <h2 style="color: #1e293b; font-size: 20px; margin-bottom: 16px;">Prescribed Medication Regimen</h2>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 40px; border: 1px solid #6366f1;">
        <thead>
          <tr style="background-color: #6366f1; color: #ffffff;">
            <th style="padding: 16px; text-align: center; font-weight: 600; border: 1px solid #c7d2fe; width: 5%;">#</th>
            <th style="padding: 16px; text-align: left; font-weight: 600; border: 1px solid #c7d2fe; width: 30%;">Drug / Medication</th>
            <th style="padding: 16px; text-align: left; font-weight: 600; border: 1px solid #c7d2fe; width: 20%;">Dosage</th>
            <th style="padding: 16px; text-align: left; font-weight: 600; border: 1px solid #c7d2fe; width: 25%;">Frequency</th>
            <th style="padding: 16px; text-align: left; font-weight: 600; border: 1px solid #c7d2fe; width: 20%;">Duration</th>
          </tr>
        </thead>
        <tbody>
          \${drugRows}
        </tbody>
      </table>

      <!-- Clinical Summary -->
      <h2 style="color: #1e293b; font-size: 20px; margin-bottom: 16px;">Clinical Summary</h2>
      <div style="background-color: #eff6ff; border: 2px solid #6366f1; border-left-width: 6px; padding: 20px; color: #1e293b; line-height: 1.6; font-size: 15px;">
        \${clinicalSummary}
      </div>
    </div>
    \`;
    
    return html;
  };
`;

app = app.substring(0, generateHTMLStart) + newFunction + app.substring(generateHTMLEnd);
fs.writeFileSync('frontend/src/App.jsx', app);
console.log('Update complete');
